CREATE DATABASE "abuse_db";

\connect "abuse_db";

CREATE TABLE "public"."abusive_host_rules" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "host" inet NOT NULL,
    "blocked" smallint NOT NULL,
    "regions" text,
    "notes" text,
    CONSTRAINT "abusive_host_rules_host_key" UNIQUE ("host"),
    CONSTRAINT "abusive_host_rules_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "host_index" ON "public"."abusive_host_rules" USING btree ("host");


CREATE TABLE "public"."databasechangelog" (
    "id" character varying(255) NOT NULL,
    "author" character varying(255) NOT NULL,
    "filename" character varying(255) NOT NULL,
    "dateexecuted" timestamp NOT NULL,
    "orderexecuted" integer NOT NULL,
    "exectype" character varying(10) NOT NULL,
    "md5sum" character varying(35),
    "description" character varying(255),
    "comments" character varying(255),
    "tag" character varying(255),
    "liquibase" character varying(20),
    "contexts" character varying(255),
    "labels" character varying(255),
    "deployment_id" character varying(10)
) WITH (oids = false);


CREATE TABLE "public"."databasechangeloglock" (
    "id" integer NOT NULL,
    "locked" boolean NOT NULL,
    "lockgranted" timestamp,
    "lockedby" character varying(255),
    CONSTRAINT "databasechangeloglock_pkey" PRIMARY KEY ("id")
) WITH (oids = false);