CREATE DATABASE "message_db";

\connect "message_db";

CREATE TABLE "public"."databasechangelog" (
    "id" character varying(255) NOT NULL,
    "author" character varying(255) NOT NULL,
    "filename" character varying(255) NOT NULL,
    "dateexecuted" timestamp NOT NULL,
    "orderexecuted" integer NOT NULL,
    "exectype" character varying(10) NOT NULL,
    "md5sum" character varying(35),
    "description" character varying(255),
    "comments" character varying(255),
    "tag" character varying(255),
    "liquibase" character varying(20),
    "contexts" character varying(255),
    "labels" character varying(255),
    "deployment_id" character varying(10)
) WITH (oids = false);


CREATE TABLE "public"."databasechangeloglock" (
    "id" integer NOT NULL,
    "locked" boolean NOT NULL,
    "lockgranted" timestamp,
    "lockedby" character varying(255),
    CONSTRAINT "databasechangeloglock_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


CREATE TABLE "public"."messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "type" smallint NOT NULL,
    "relay" text NOT NULL,
    "timestamp" bigint NOT NULL,
    "source" text,
    "source_device" integer,
    "destination" text NOT NULL,
    "destination_device" integer NOT NULL,
    "message" bytea,
    "content" bytea,
    "guid" uuid,
    "server_timestamp" bigint,
    "source_uuid" uuid,
    CONSTRAINT "messages_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "destination_and_type_index" ON "public"."messages" USING btree ("destination", "destination_device", "type");

CREATE INDEX "destination_index" ON "public"."messages" USING btree ("destination", "destination_device");

CREATE INDEX "guid_index" ON "public"."messages" USING btree ("guid");
