version: '3.3'
services:

  postgresql_accounts_db:
    image: 'postgres:11'
    container_name: db_accounts
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounts_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5431:5432'
    volumes:
      - ./postgres/accounts_db.sql:/docker-entrypoint-initdb.d/init.sql
      - './postgres/accounts_db:/var/lib/postgresql/data'
    networks:
      - default

  postgresql_message_db:
    image: 'postgres:11'
    container_name: db_message
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: message_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/message_db.sql:/docker-entrypoint-initdb.d/init.sql
      - './postgres/message_db:/var/lib/postgresql/data'
    networks:
      - default
      
  postgresql_abuse_db:
    image: 'postgres:11'
    container_name: db_abuse
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abuse_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes:
      - ./postgres/abuse_db.sql:/docker-entrypoint-initdb.d/init.sql
      - './postgres/abuse_db:/var/lib/postgresql/data'
    networks:
      - default

  redis:
    image: 'redis:5'
    container_name: redis
    command: redis-server --port 6379
    ports:
      - '6379:6379'
    volumes:
      - './redis:/data'
    networks:
      - default

  turn-server:
    build:
      context: ./turn-server
      dockerfile: Dockerfile
    container_name: turn-server
    restart: always
    ports:
      - '3478:3478/udp'
      - '3478:3478/tcp'
      - '5349:5349/udp'
      - '5349:5349/tcp'
    volumes:
      - ./config/turnserver.conf:/etc/coturn/turnserver.conf
    networks:
      - default

  signal-server:
    build:
      context: ./signal-server
      dockerfile: Dockerfile
    container_name: signal-server
    restart: always
    volumes:
      - './config:/config'
    ports:
      - '8080:8080'
      - '8081:8081'
    networks:
      - default
    depends_on:
      - postgresql_accounts_db
      - postgresql_message_db
      - postgresql_abuse_db
      - turn-server
      - redis

#   redis_commander:
#     container_name: redis_commander
#     image: 'rediscommander/redis-commander:latest'
#     hostname: redis-commander
#     ports:
#       - '8001:8081'
#     links:
#       - redis_main
#     environment:
#       - 'REDIS_HOSTS=main:redis_main:6379, replica:redis_replication:6380'

  # adminer:
  #   container_name: adminer
  #   image:  adminer:latest
  #   ports:  
  #     - 8000:8080
  #   links: 
  #     - postgresql_accounts_db
  #     - postgresql_message_db
  #     - postgresql_abuse_db
  #   environment: 
  #     ADMINER_DESIGN: nette
  #   networks:
  #     - default